name: Observer

# Which field will we use to display instances of this model in our app
displayField: email

fields:
  - name: firstName
    type: String
  - name: lastName
    type: String
  - name: email
    type: String