name: Taxonomy

# Which field will we use to display instances of this model in our app
displayField: scientificName

fields:
  - name: scientificName
    type: String
  - name: kingdom
    type: String
  - name: phylum
    type: String
  - name: class
    type: String
  - name: order
    type: String
  - name: family
    type: String
  - name: genus
    type: String
  - name: species
    type: String