# Which model document types should be accessible directly?
# These should only be root level doc types.
# Exclude child (e.g. nested) documents that users can only reach through a parent.
---
visibleItems:
  # - AdLibitum           # Only accessible via a diary or contact
  # - Audio               # Only accessible via a diary or contact or adLibitum or focalSample
  # - Behavior            
  # - BiologicalSample    # Only accessible via a diary or contact
  # - Contact             # Only accessible via a diary
  - Diary
  # - FocalDatum          # Only accessible via a focalSample
  # - FocalSample         # Only accessible via a contact
  # - Measurement         # Only accessible via a contact
  # - Media               # Only accessible via a diary or contact or adLibitum or focalSample
  # - Observer
  # - Photo               # Only accessible via a diary or contact or adLibitum or focalSample
  # - PlantSample         # Only accessible via a diary or contact
  # - Subject
  # - Taxonomy
  # - Video               # Only accessible via a diary or contact or adLibitum or focalSample
